# Generated by Django 5.2 on 2025-04-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_1', '0002_randommodel_random_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
